name = "edge-project-sample"
main = "src/index.ts"
compatibility_date = "2023-03-06"
[[ d1_databases ]]
binding = "edge_sample_db_binding"
database_name = "edge_sample_db"
database_id = "e3ba9bbf-d38e-4c93-b537-8e71581536fe"